 build_image:
  before_script:
    #- Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - git remote set-url origin https://tunisiano187:${Gitlab_api}@gitlab.com/chocolatey-packages/tools/chocolatey-ps-validator.git
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_LOGIN
  script:
    - Write-Host "Setup module"
    - ./Update_script.ps1
  after_script:
    - Get-ChildItem -Path ./ -Include *.nupkg -Recurse -File | Move-Item -Destination ./upload/ -Force
    - Get-ChildItem -Path ./ -Include Update-AUPacakges.md -Recurse -File | Move-Item -Destination ./upload/ -Force
    - git checkout -B master
    - git add -u :/
    - git commit -m '[skip ci] commit from CI runner'
    - git push --follow-tags origin master
  artifacts:
    paths:
        - upload/
    expire_in: 1 week
  tags:
    - shared-windows
    - windows
